### ISSUE TITLE
PUT method not supported via HTTP

### ISSUE THREAD

**Issue by mmccool** [thingweb/thingweb-directory#12] opened 2017-11-05 22:57 UTC
When trying to update (using PUT) a TD previously created with POST via the HTTP interface, the following error is received.   I am getting this with my OCF metadata bridge, where I want to update TDs "in place".   As a workaround for now I will use POST/DELETE in place of PUT, but this is inelegant (and is not exactly equivalent, as it also changes the keys to the entry in the Thing Directory...).

PUT does seem to work through CoAP, so this may be a HTTP/CoAP bridge issue.

WOT-OCF-GEN-DEBUG 11409: Status: 405
WOT-OCF-GEN-DEBUG 11409: Headers: {"date":"Sun, 05 Nov 2017 22:35:45 GMT","cache-control":"must-revalidate,no-cache,no-store","content-type":"text/html;charset=iso-8859-1","content-length":"361","connection":"close","server":"Jetty(9.3.z-SNAPSHOT)"}
WOT-OCF-GEN-DEBUG 11409: Thing Directory PUT Response: 405
WOT-OCF-GEN-DEBUG 11409: Error updating TD  Intel-OCF-fb6481e0-79e1-4be0-99c1-df9bcbb898a0
Body: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 405 </title>
</head>
<body>
<h2>HTTP ERROR: 405</h2>
<p>Problem accessing /td/a45b5e29. Reason:
<pre>    HTTP method PUT is not supported by this URL</pre></p>
<hr /><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.z-SNAPSHOT</a><hr/>
</body>
</html>

**Comment by vcharpenay** [comment] 2018-03-18 22:08
Must have been fixed in v0.8 (didn't check though, since the code base has significantly changed, I could not reproduce the bug).

**Closed by vcharpenay** 2018-03-18 22:08 UTC
